# Generated by Django 4.0.3 on 2022-04-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
                ('market_price', models.IntegerField()),
                ('tag_config_ids', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=20)),
                ('tag_names', models.CharField(max_length=20)),
                ('house_price', models.IntegerField()),
            ],
        ),
    ]
