# Generated by Django 4.0.3 on 2022-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='facility',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='livenums',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
