# Generated by Django 4.0.3 on 2022-04-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_house_area_house_facility_house_livenums_house_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='views',
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='livenums',
            field=models.IntegerField(default=1),
        ),
    ]
