# Generated by Django 4.0.3 on 2022-04-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_remove_house_views_alter_house_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='tag_config_ids',
        ),
    ]
