# Generated by Django 4.0.3 on 2022-04-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_remove_house_tag_config_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='status',
        ),
    ]
