# Generated by Django 4.0.3 on 2022-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_remove_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='facility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_price',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='house',
            name='market_price',
            field=models.IntegerField(default=100),
        ),
    ]
