# Generated by Django 4.0.3 on 2022-04-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_alter_house_decs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='tag_names',
            new_name='tag',
        ),
    ]
