# Generated by Django 4.0.3 on 2022-04-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_rename_tag_names_house_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='decs',
            new_name='desc',
        ),
    ]
